[toolchain]
channel = "nightly-2024-01-01"
components = [ "cargo", "rust-src", "rust-analyzer", "clippy", "rustfmt", "miri" ]
profile = "minimal"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl" ]
