[package]
name = "npk-build"
version = "0.1.0"
edition = "2021"

[dependencies]
npk-sandbox.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio = { workspace = true, features = [ "net", "rt", "rt-multi-thread", "time", "macros", "io-util" ] }
