[package]
name = "npk-util"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror.workspace = true
tokio = {workspace = true, features = []}
rand.workspace = true
tracing.workspace = true
lockfree-object-pool.workspace = true
once_cell.workspace = true
bytes = "1"
