[package]
name = "nck-io"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes.workspace = true
tokio = { workspace = true, features = [ "fs", "io-util" ]}
rand.workspace = true

[target.'cfg(target_os = "linux")'.dependencies.nix]
workspace = true
features = [
  "fs",
]
